package com.qsp.vehicle_rental_system.entity;

import java.time.LocalDateTime;
import java.util.List;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

@Entity
@Table(name = "customers")
public class Customer {
	
	/*
	 * We cant use strategy IDENTITY and @SequenceGenerator together, it will simply not work
	 * We will get some random ids generated by DB itself like 1,35,38,etc. 
	 * So we will use SEQUENCE strategy..
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "my_custkey")
	@SequenceGenerator(name = "my_custkey", initialValue = 101, allocationSize = 1)
	private int cid;
	
	@NotBlank(message = "Name cannot be blank")
    @Size(min = 2, max = 50,
          message = "Name must contain between 2 and 50 characters")
	@Column(
	        nullable = false,
	        length = 50
	    )
	private String cname;
	
	@NotBlank(message = "Mobile number cannot be blank")
    @Pattern(
        regexp = "^[6-9][0-9]{9}$",
        message = "Mobile number must contain 10 valid digits"
    )
	@Column(
	        nullable = false,
	        unique = true,
	        length = 10
	    )
	private String mobileNo;
	
	@NotBlank(message = "Email cannot be blank")
    @Email(message = "Please provide a valid email")
	@Column(
	        nullable = false,
	        unique = true,
	        length = 100
	    )
	private String email;
	
	@CreationTimestamp
	private LocalDateTime createdAt;
	
	@UpdateTimestamp
	private LocalDateTime updatedAt;
	
	@JsonManagedReference("customer-rentals")
	@OneToMany(mappedBy = "customer")
	private List<Rental> rentals;
	
	@OneToOne(mappedBy = "customer")
	@JsonBackReference
	private Users user;
	
	public List<Rental> getRentals() {
		return rentals;
	}
	public void setRentals(List<Rental> rentals) {
		this.rentals = rentals;
	}
	public int getCid() {
		return cid;
	}
	public void setCid(int cid) {
		this.cid = cid;
	}
	public String getCname() {
		return cname;
	}
	public void setCname(String cname) {
		this.cname = cname;
	}
	public String getMobileNo() {
		return mobileNo;
	}
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	public Users getUser() {
	    return user;
	}

	public void setUser(Users user) {
	    this.user = user;
	}
	
}
