spring.application.name=vehicle-rental-system
server.port=8181
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_NAME
spring.datasource.username=postgres
spring.datasource.password=DB_PASSWORD

jwt.secret=JWT_SECRET_KEY